name: Trigger auto deployment for asvdjsavjda

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/asvdjsavjda-AutoDeployTrigger-edf6644f-3500-4732-9c2c-c5ecc692c4fb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASVDJSAVJDA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASVDJSAVJDA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASVDJSAVJDA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrrnokbmv26pdsi.azurecr.io
          registryUsername: ${{ secrets.ASVDJSAVJDA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASVDJSAVJDA_REGISTRY_PASSWORD }}
          containerAppName: asvdjsavjda
          resourceGroup: vgtestcli-rg
          imageToBuild: acrrnokbmv26pdsi.azurecr.io/asvdjsavjda:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


